//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_mvc_Dbfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uruntablo
    {
        public int Urunid { get; set; }
        public string Urunadi { get; set; }
        public string Urunmarka { get; set; }
        public decimal Urunfiyat { get; set; }
        public int Urunadet { get; set; }
    }
}
